language: ruby
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.3
  - 2.4.1
  - 2.5.3
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.2.gemfile
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: Gemfile
